---
# tasks file for ansible-docker-base
- name: Ensure Software is installed
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - python-pip

- name: Installed docker-py
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-py

- name: Ensure docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: true

- name: Starting Docker container {{ spl_docker_image }}
  docker_container:
    name: '{{ spl_container_name }}'
    image: '{{ spl_docker_image }}'
    command: '{{ hec_token }}'
    state: started
    ports:
     - "514:514"
     - "8000:8000"
     - "8088:8088"
  when: 
    - container_name is defined
    - docker_image is defined
